# This is a basic workflow to help you get started with Actions

name: twitter-sentiment

# Controls when the action will run. 
on:
#   # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    - cron: '0 12 * * *' # runs at 12:00 UTC everyday
    - cron: '59 23 * * *' # runs at 12:00 UTC everyday

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
  
      # Runs a single command using the runners shell
      - name: Install dependencies
        run: | 
            python -m pip install pandas
            python -m pip install numpy
            python -m pip install matplotlib
            python twitter-json.py
            python twitter-stock-sentiment-analysis.py
      - name: commit files
        run: |
          git config --local user.email "evayl2@illinois.edu"
          git config --local user.name "evayl2"
          git add -A
          git commit -m "update data" -a
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{secrets.GITHUB_TOKEN }}
          branch: main  
